### ISSUE TITLE
Add Bluetooth monitoring 

### ISSUE THREAD

**Issue by MaluNoPeleke** [asksven/BetterWifiOnOff#101]
Could you please extend the  functionality of this application to Bluetooth, too? 
Would be nice especially on Tablets which could be used a long time idling.

**Comment by asksven** [comment]
IMHO the bluetooth energy management does not require a specific handling as its idle-consumption is near to 0. Do you have data that would show the need for controlling BT as Wifi?

**Comment by MaluNoPeleke** [comment]
Sorry, no data but I thought better safe a little bit battery than nothing. Especially tablets can idle for 10 days or more and then you could see a difference. Not every Android device has a current Bluetooth stack with ultralow ppower.

**Comment by asksven** [comment]
I have never seen the need for this as none of my devices (starting from a htc desire) ever showed any readable sign of drain. You may want to check betterbatterystats and see if you can provide a reading showing wakelocks of Alarms coming from the bt stack. 
If a reading shows potential if am willing to add code to process that but as of now I doubt that the effort is worth it. You can of course convince me that I am wrong

**Comment by asksven** [comment]
Will not implement: there is no ground in believeing that BT always on consumes power. Besides: this is BWOF not BBTOF
