### ISSUE TITLE
[feature] add consistently show plug/unplug operatiins

### ISSUE THREAD

**Issue by asksven** [asksven/BetterWifiOnOff#117]
I have the option enabled for turning Wifi on when plugged. In the events log I see no notification of "Power was connected". I do see an event when phone is unplugged: "Power was disconnected". It is just a suggestion to be considered, to have a complete overview. Processing is working as set.

**Comment by chrone81** [comment]
+1. Will too many logs slow down emmc io  performance and use morr battery juice?
