### ISSUE TITLE
Newest version 2.1 is broken on galaxy S II

### ISSUE THREAD

**Issue by nottud** [asksven/BetterWifiOnOff#128]
When you close the app it crashes and does not work - it is as if the service is no longer running. This occurs when the app is closed - minimising by the home button the app works fine - but you have you keep it in the foreground.

If having just crashed in this way, launching again just gives a black screen.

---

Previous version 2.0 works fine.

**Comment by asksven** [comment]
Could you please send a logcat showing the crash?

**Comment by asksven** [comment]
Closed as that can not be reproduced and no log was provided
