### ISSUE TITLE
[feature] keep wifi active when data is transferring and screen goes off

### ISSUE THREAD

**Issue by lordgoata** [asksven/BetterWifiOnOff#17]
Just installed on my TF101 and was updating a load of apps from Google Play. The screen went off, and a few minutes later I unlocked the screen and the WiFi was off (and then reconnected as expected).

It would be nice if the WiFi wouldn't drop when the screen goes off if there is data transferring (over a given threshold I guess), to avoid aborting any downloads that are in progress.

**Comment by asksven** [comment]
```
        DownloadManager dl = (DownloadManager) mContext
                .getSystemService(Context.DOWNLOAD_SERVICE);
        Cursor query = dl.query(new DownloadManager.Query()
                .setFilterByStatus(DownloadManager.STATUS_PENDING
                        | DownloadManager.STATUS_RUNNING));
```
