### ISSUE TITLE
[feature] add a rule to notify user when wifi is on but no connection could be achieved

### ISSUE THREAD

**Issue by asksven** [asksven/BetterWifiOnOff#18]

**Comment by whittet** [comment]
The Sentry app does not enable Wifi if no connection could be activated. Suggest that behavior.

**Comment by asksven** [comment]
Sorry but could you be more specific. What behavior / use case do you request that is not present already?

**Comment by whittet** [comment]
Nevermind, like it as it!

**Comment by chrone81** [comment]
I hope it won't be so intrusive like the popup notification from best wifi app each 10 seconds it tells no apn found. Lol

Would love to have wifi disabled if no saved apn found after 15-30 seconds linger.

**Comment by whittet** [comment]
"WIFI power saver" turns off WIFI when connection lost for 5+ minutes

**Comment by asksven** [comment]
(In reply to comment #5)

> "WIFI power saver" turns off WIFI when connection lost for 5+ minutes

**Comment by asksven** [comment]
(In reply to comment #4)

> I hope it won't be so intrusive like the popup notification from best wifi app
> each 10 seconds it tells no apn found. Lol
> 
> Would love to have wifi disabled if no saved apn found after 15-30 seconds
> linger.
> (In reply to comment #4)
> I hope it won't be so intrusive like the popup notification from best wifi app
> each 10 seconds it tells no apn found. Lol
> 
> Would love to have wifi disabled if no saved apn found after 15-30 seconds
> linger.
> As the feature says this is only a matter of notifying the user, not about doing anything automatic. What I was thinking of was to add a green glow to the sticky icon, that's all

**Comment by asksven** [comment]
Replaced by #130
