### ISSUE TITLE
[feature] add wifi-on only if wifi is off by this app.

### ISSUE THREAD

**Issue by waynee** [asksven/BetterWifiOnOff#19]
It is keep going on even I close the WiFi manually.

**Comment by azrash** [comment]
true, another workaround is enabling a simple shortcut at launcher that toggles BetterWifiOn or a simple widget. as for now, killing the app in running services should do the trick

**Comment by asksven** [comment]
or just disable it from preferences.

**Comment by waynee** [comment]
It is not a workaround if I need a addition workaround manually. Why do I still need to use this apps?

**Comment by azrash** [comment]
true, i find myself having to disable the app manually when I am on the move
